services:
    type: web
    name: skyline-gadgets-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: 'npm run build'
    startCommand: 'npm start'
    envVars:
        key: NPM_CONFIG_PRODUCTION
        value: 'false'
        key: NODE_ENV
        value: 'production'
        key: NODE_VERSION
        value: '18'
